# Partner Distribution Configuration File

[Global]
id=enterprise-mozsandbox
version=1.0
about=Enterprise MozSandbox

[Preferences]
enterprise.console.address=https://stormkeeper.sandbox.moz-enterprise.com
