# Partner Distribution Configuration File

[Global]
id=enterprise-mozcloud-prod
version=1.0
about=Enterprise MozCloud Prod

[Preferences] 
enterprise.console.address=https://prod.fx-enterprise.prod.webservices.mozgcp.net
