# Partner Distribution Configuration File

[Global]
id=enterprise-mozcloud-stage
version=1.0
about=Enterprise MozCloud Stage

[Preferences]
enterprise.console.address=https://stage.fx-enterprise.nonprod.webservices.mozgcp.net
